app/src/twitter_scraper/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.src.twitter_scraper.scraper.urls')),
]

app/src/twitter_scraper/scraper/urls.py
from django.urls import path

from .views import (index, like_unlike_tweet, tweet_detail_view,
                    tweets_list_view)

app_name = 'scraper'
urlpatterns = [
    path('', index, name='index'),
    path('tweets/', tweets_list_view, name='tweets'),
    path('tweet/<int:id>', tweet_detail_view, name='tweet'),
    path('tweet/<int:id>/like/', like_unlike_tweet, name='like'),
    path('tweet/<int:id>/unlike/', like_unlike_tweet, name='unlike'),
]

app/src/twitter_scraper/scraper/models.py
import pytest
from django.db import models


class Tweet(models.Model):
    """
    This is the Tweet model. It stores data related to the Tweet object

    Fields:
        tweet_id: Unique ID for each Tweet
        tweet_text: Actual Tweet text
        tweet_rts: Number of Retweets on the Tweet
        tweet_likes: Number of Likes on the Tweet
        tweet_replies: Number of Replies on the Tweet
    """
    tweet_id = models.CharField(max_length=50)
    tweet_text = models.TextField(max_length=280)
    tweet_rts = models.PositiveIntegerField()
    tweet_likes = models.PositiveIntegerField()
    tweet_replies = models.PositiveIntegerField()
    tweet_author = models.CharField(max_length=50)
    liked = models.BooleanField(default=False)

    def __str__(self):
        return self.tweet_text

app/src/twitter_scraper/scraper/forms.py
from django import forms


class InputForm(forms.Form):
    username = forms.CharField(
        max_length=15,
        help_text='Enter Twitter username from a public account')
    no_of_tweets = forms.IntegerField(
        min_value=0,
        max_value=900,
        help_text='Enter the number of Tweets to fetch')

app/src/twitter_scraper/scraper/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import HttpResponseRedirect, get_object_or_404, render
from django.urls import reverse

from .forms import InputForm
from .models import Tweet
from .tasks import fetch_tweets

logger = logging.getLogger('main')
logger.setLevel(logging.DEBUG)


def like_unlike_tweet(request, id):
    tweet = Tweet.objects.get(tweet_id=id)

    try:
        settings.CLIENT.like(tweet.tweet_id)
    except Exception:
        logger.error("Problem accessing API")

    if tweet.liked is False:
        Tweet.objects.filter(tweet_id=tweet.tweet_id).update(
            liked=1, tweet_likes=tweet.tweet_likes + 1)
        logger.info("Tweet liked. Tweet ID: %s", tweet.tweet_id)

    else:
        Tweet.objects.filter(tweet_id=tweet.tweet_id).update(
            liked=0, tweet_likes=tweet.tweet_likes - 1)
        logger.info("Tweet unliked. Tweet ID: %s", tweet.tweet_id)

    return HttpResponseRedirect(reverse('scraper:tweet', args=[tweet.id]))


def index(request):

    if request.method == 'POST':
        form = InputForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            no_of_tweets = form.cleaned_data['no_of_tweets']

            try:
                fetch_tweets.delay(username, no_of_tweets)
                logger.info("Tweets fetched")
            except Exception:
                print("Error retrieving Tweets")
                logger.error("Error retrieving Tweets")

        messages.info(
            request,
            'Reload page to view newly retrieved Tweets'
        )
        return HttpResponseRedirect('tweets')

    form = InputForm()

    context = {'form': form}
    return render(request, "scraper/index.html", context)


def tweets_list_view(request):
    tweet_list = Tweet.objects.all().order_by('-id')
    paginator = Paginator(tweet_list, 10)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'tweet_list': tweet_list,
        'page_obj': page_obj,
    }

    return render(request, "scraper/tweets_list.html", context)


def tweet_detail_view(request, id):
    tweet = get_object_or_404(Tweet, id=id)

    context = {
        'tweet': tweet,
    }

    return render(request, 'scraper/tweet_detail.html', context)

app/src/twitter_scraper/scraper/templates/scraper/all_tweets.html
{% extends "scraper/base.html" %}
{% block content %}

<h3>All Tweets</h3>

<div class="d-flex align-items-center justify-content-center">
    
    <table class="table">
        {% if tweet_list %}
            <thead>
                <th scope="col">Tweet </th>
                <th scope="col">Retweets</th>
                <th scope="col">Likes</th>
                <th scope="col">Replies</th>
            </thead>

        {% endif %}

        {% for tweet in tweet_list %}

            <tbody>
                <tr>
                    <td><a href="{% url 'scraper:tweet' tweet.pk %}">{{ tweet.tweet_text }}</a></td>
                    
                    <td>{{ tweet.tweet_rts }}</td>
                    <td>{{ tweet.tweet_likes }}</td>
                    <td>{{ tweet.tweet_replies }}</td>
                </tr>
            </tbody>
            
        {% endfor %}
    </table>
</div>
<div class="pagination">
    <span class="page-links">
        {% if page_obj.has_previous %}
            <a href="/?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
        {% if page_obj.has_next %}
            <a href="/?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
    
<!-- 
    <h3>Latest Tweet</h3>
    <p>{{ latest_tweet.tweet_id }}</p>
    <p>{{ latest_tweet.tweet_text}}</p>
    <span>Likes: {{ latest_tweet.tweet_likes }}     Retweets: {{ latest_tweet.tweet_rts }}     Replies: {{ latest_tweet.tweet_replies }}</span>
-->
{% endblock content %}

app/src/twitter_scraper/scraper/templates/scraper/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="refresh" content="10">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Twitter Scraper</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'scraper:index' %}">Twitter Scraper</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'scraper:index' %}">Home</a>
                    <a class="nav-link" href="{% url 'scraper:tweets' %}">All Tweets</a>
                </div>
            </div>
        </div>
    </nav>
    {% endblock navbar %}

    <div class="container">
        <div class="row align-items-center">
            <div class="col">
            {% block content %}

            {% endblock content %}
            </div>
        </div>
    </div>
        
</body>
</html>

app/src/twitter_scraper/scraper/templates/scraper/email_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Twitter Scraper</title>

</head>

    <table style="min-width: 300px;background: rgba(0, 0, 0, 0.15); overflow: hidden; width: 100%; height: 100%;">
        <tbody style="width: 100%;">
            <tr style="position: relative; width: 100%; padding: .5rem; background: #161616;">
                <th style="width: 100%;" colspan="2">New Tweet Retrieved</th>
            </tr>

            <tr style="width: 100%;">
                <th style="width: 100%;" colspan="2"><hr style="width: 60%; border: 1px solid #161616;" ></th>
            </tr>

            <tr style="position: relative; width: 100%;" colspan="2">
                <th style="width: 100%;" colspan="2"><span style="font-family: Arial, Helvetica, sans-serif; font-size: .75rem; font-weight: 100; color: #828282; padding:0 .5rem; text-align: center;">{{dt_string}}</span></th>
            </tr>
            
            <tr style="position: relative; width: 100%; padding: .5rem;">
                <th style="width: 100%;" colspan="2"><p style="font-family: Arial, Helvetica, sans-serif; font-size: 1.25rem; font-weight: 500; color: #161616; padding: 0 .5rem; text-align: center; max-width: 500px;">{{tweet_text}}</p></th>
            </tr>

            <tr style="position: relative; width: 100%; padding: 0 .5rem; text-align: center;">
                <td><p style="font-family: Arial, Helvetica, sans-serif; font-size: 1rem; font-weight: 400; color: #828282; padding:0 .5rem; text-align: center;">Retweets: {{tweet_rts}}</p></td>
                <td><p style="font-family: Arial, Helvetica, sans-serif; font-size: 1rem; font-weight: 200; color: #828282; padding:0 .5rem; text-align: center;">Likes: {{tweet_likes}}</p></td>
                <td><p style="font-family: Arial, Helvetica, sans-serif; font-size: 1rem; font-weight: 200; color: #828282; padding:0 .5rem; text-align: center;">Replies: {{tweet_replies}}</p></td>
            </tr>
    
        </tbody>
    </table>
    
</html>

app/src/twitter_scraper/scraper/templates/scraper/index.html
{% extends "scraper/base.html" %}
{% include "scraper/messages.html" %}
{% block content %}

    <form class="mx-auto" style="width: 400px" action = "" method = "post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group p-2 mb-3">
            {{ form.username.errors }}
            <label class="form-label" for="id_username">Username: </label>
            <input class="form-control" type="text" name="username" maxlength="15" required="" id="id_username">
            <small class="form-text text-muted">{{ form.username.help_text }}</small>
        </div>
        <div class="form-group p-2 mb-3">
            {{ form.no_of_tweets.errors }}
            <label class="form-label" for="id_username">No of Tweets: </label>
            <input class="form-control" type="number" name="no_of_tweets" min="0" max="900" required="" id="id_no_of_tweets">
            <small class="form-text text-muted">{{ form.no_of_tweets.help_text }}</small>
        </div>
        <input class="btn btn-primary p-2 m-2" type="submit" value="Submit">
    </form>

{% endblock content %}
    

app/src/twitter_scraper/scraper/templates/scraper/messages.html
{% block content %}
{% for message in messages %}

<div class="container-fluid p-0">
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" >
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>

{% endfor %}
{% endblock content %}

app/src/twitter_scraper/scraper/templates/scraper/tweet_detail.html
{% extends "scraper/base.html" %}
{% block content %}
<div class="d-flex align-items-center justify-content-center">
    <div class="card m-2" style="width: 24rem;">
        <div class="card-body justify-content-center align-content-center">
            <h4 class="card-title">{{ tweet.tweet_author }}</h4>
            <p class="card-text">{{ tweet.tweet_text }}</p>
            <h6 class="card-footer mb-2">
                <p><span class="text-muted"> Likes: </span>{{ tweet.tweet_likes }}</p>  
                <p><span class="text-muted"> Retweets: </span>{{ tweet.tweet_rts }}</p>  
                <p><span class="text-muted"> Replies: </span>{{ tweet.tweet_replies }}</p>  
            </h6>

            {% if tweet.liked is False %}
                <a class="btn btn-primary" href="{% url 'scraper:like' id=tweet.tweet_id %}">Like</a>
            {% elif tweet.liked is True %}
                <a class="btn btn-danger" href="{% url 'scraper:unlike' id=tweet.tweet_id %}">Unlike</a>
            {% endif %}

            <a class="btn btn-secondary" href="{% url 'scraper:tweets' %}">Back</a>
        </div>
    </div>
</div>

{% endblock content %}

app/src/twitter_scraper/scraper/templates/scraper/tweets_list.html
{% extends "scraper/base.html" %}
{% block content %}

<h3>All Tweets</h3>
{% include "scraper/messages.html" %}


<div class="d-flex align-items-center justify-content-center">
    
    <table class="table">
        {% if page_obj %}
            <thead>
                <th scope="col">Tweet </th>
                <th scope="col">Retweets</th>
                <th scope="col">Likes</th>
                <th scope="col">Replies</th>
            </thead>

        {% endif %}

        {% for tweet in page_obj %}

            <tbody>
                <tr>
                    <td><a href="{% url 'scraper:tweet' tweet.id %}">{{ tweet.tweet_text }}</a></td>
                    
                    <td>{{ tweet.tweet_rts }}</td>
                    <td>{{ tweet.tweet_likes }}</td>
                    <td>{{ tweet.tweet_replies }}</td>
                </tr>
            </tbody>
            
        {% endfor %}
    </table>
</div>
<div class="pagination">
    <span class="page-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
    
<!-- 
    <h3>Latest Tweet</h3>
    <p>{{ latest_tweet.tweet_id }}</p>
    <p>{{ latest_tweet.tweet_text}}</p>
    <span>Likes: {{ latest_tweet.tweet_likes }}     Retweets: {{ latest_tweet.tweet_rts }}     Replies: {{ latest_tweet.tweet_replies }}</span>
-->
{% endblock content %}